Winners model
tydolla00/Project-RDC pull request #12
Opened 2024-11-12 14:57 UTC by Shargrove09

Add more relations to better track winner of sets and matches. 
Fix some inconsistencies in schema

2024-11-12 20:03 UTC, tydolla00 commented on prisma/schema.prisma
> +  matchWins      Match[]         @relation("matchWinner")
Don't forget map _ for camelCases

2024-11-13 01:15 UTC, tydolla00 requested changes
add _s to db model

2024-11-13 04:16 UTC, Shargrove09 reviewed
See text regarding _s

2024-11-13 04:21 UTC, tydolla00 commented on prisma/schema.prisma
> +  matchWinner    Player[]        @relation("matchWinner")
I think we can just omit them all then.

2024-11-13 14:31 UTC, Shargrove09 reviewed
Done

2024-11-13 14:36 UTC, merged